import = [
    # "~/.config/alacritty/my-theme.toml"
]

[shell]
program = "/bin/zsh"

[window]
opacity = 0.95

[cursor]
style.shape = "Block"
style.blinking = "On"

[font]
# 日本語表記のテスト
size = 11.0
normal.family = "UDEV Gothic 35NF"
normal.style = "Regular"
bold.family = "UDEV Gothic 35NF"
bold.style = "Bold"
italic.family = "UDEV Gothic 35NF"
italic.style = "Italic"
bold_italic.family = "UDEV Gothic 35NF"
bold_italic.style = "Bold Italic"
