# NOTE: Set this value to True for inline Japanese input in Alacritty.
# Ref:
#     https://ikmnjrd.github.io/blog/fcitx-xim-config
#     https://dev.to/nabbisen/fcitx--1n59
# Use On The Spot Style (Needs restarting)
UseOnTheSpot=True

